get http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "hehe xd",
    "author": "Na",
    "url": "https://reactjs.org/docs/hooks-state.html",
    "likes": "232"
}